import type { SidebarItem } from '../../../shared/types'
import { ROUTES } from '../../../shared/constants'

export const spSidebarConfig: SidebarItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    path: ROUTES.SP_DASHBOARD,
    icon: '📊',
  },
  {
    id: 'companies',
    label: 'Companies',
    path: ROUTES.SP_COMPANIES,
    icon: '🏢',
    children: [
      { id: 'all', label: 'All Companies', path: ROUTES.SP_COMPANIES, icon: '📋' },
      { id: 'active', label: 'Active', path: `${ROUTES.SP_COMPANIES}?status=active`, icon: '✅' },
      { id: 'suspended', label: 'Suspended', path: `${ROUTES.SP_COMPANIES}?status=suspended`, icon: '🚫' },
    ],
  },
  {
    id: 'freelancers',
    label: 'Freelancers',
    path: ROUTES.SP_FREELANCERS,
    icon: '👨‍💼',
  },
  {
    id: 'subscriptions',
    label: 'Subscriptions',
    path: ROUTES.SP_SUBSCRIPTIONS,
    icon: '💳',
    children: [
      { id: 'plans', label: 'Plans', path: `${ROUTES.SP_SUBSCRIPTIONS}/plans`, icon: '📋' },
      { id: 'active-subs', label: 'Active', path: `${ROUTES.SP_SUBSCRIPTIONS}?status=active`, icon: '✅' },
      { id: 'reports', label: 'Reports', path: `${ROUTES.SP_SUBSCRIPTIONS}/reports`, icon: '📊' },
    ],
  },
  {
    id: 'staff',
    label: 'Admin Staff',
    path: ROUTES.SP_STAFF,
    icon: '👨‍💼',
    children: [
      { id: 'all-staff', label: 'All Staff', path: ROUTES.SP_STAFF, icon: '👥' },
      { id: 'permissions', label: 'Permissions', path: `${ROUTES.SP_STAFF}/permissions`, icon: '🔒' },
    ],
  },
  {
    id: 'permissions',
    label: 'Permissions',
    path: ROUTES.SP_PERMISSIONS,
    icon: '🔐',
  },
  {
    id: 'support',
    label: 'Support Tickets',
    path: ROUTES.SP_SUPPORT,
    icon: '🎫',
    badge: '12',
    children: [
      { id: 'support-ticket-system', label: 'Ticket System', path: ROUTES.SP_SUPPORT, icon: '🎫' },
      { id: 'support-ticket-details', label: 'Ticket Details', path: `${ROUTES.SP_SUPPORT}/tickets/TKT-001`, icon: '📋' },
      { id: 'support-conversation', label: 'Conversation Thread', path: `${ROUTES.SP_SUPPORT}/conversation`, icon: '💬' },
      { id: 'support-workflow', label: 'Status Workflow', path: `${ROUTES.SP_SUPPORT}/workflow`, icon: '✅' },
      { id: 'support-analytics', label: 'Support Analytics', path: `${ROUTES.SP_SUPPORT}/analytics`, icon: '📊' },
    ],
  },
  {
    id: 'finance',
    label: 'Finance',
    path: ROUTES.SP_FINANCE,
    icon: '💰',
    children: [
      { id: 'revenue-dashboard', label: 'Revenue Dashboard', path: `${ROUTES.SP_FINANCE}/revenue`, icon: '📈' },
      { id: 'invoice-tables', label: 'Invoice Tables', path: `${ROUTES.SP_FINANCE}/invoices`, icon: '📄' },
      { id: 'subscription-analytics', label: 'Subscription Analytics', path: `${ROUTES.SP_FINANCE}/subscription-analytics`, icon: '📊' },
      { id: 'payouts', label: 'Payouts', path: `${ROUTES.SP_FINANCE}/payouts`, icon: '🏦' },
      { id: 'transactions', label: 'Transaction History', path: `${ROUTES.SP_FINANCE}/transactions`, icon: '💳' },
      { id: 'tax-summaries', label: 'Tax Summaries', path: `${ROUTES.SP_FINANCE}/tax-summaries`, icon: '🧾' },
    ],
  },
  {
    id: 'monitoring',
    label: 'System Monitoring',
    path: ROUTES.SP_MONITORING,
    icon: '🔍',
    children: [
      { id: 'api-requests', label: 'Realtime API Requests', path: `${ROUTES.SP_MONITORING}/api-requests`, icon: '📡' },
      { id: 'server-load', label: 'Server Load', path: `${ROUTES.SP_MONITORING}/server-load`, icon: '🖥️' },
      { id: 'websockets', label: 'Websocket Connections', path: `${ROUTES.SP_MONITORING}/websockets`, icon: '🔌' },
      { id: 'active-sessions', label: 'Active Sessions', path: `${ROUTES.SP_MONITORING}/active-sessions`, icon: '👥' },
      { id: 'storage', label: 'Storage Analytics', path: `${ROUTES.SP_MONITORING}/storage`, icon: '💾' },
      { id: 'registrations', label: 'User Registrations', path: `${ROUTES.SP_MONITORING}/registrations`, icon: '📝' },
      { id: 'dead-accounts', label: 'Dead Accounts', path: `${ROUTES.SP_MONITORING}/dead-accounts`, icon: '📦' },
      { id: 'failed-requests', label: 'Failed Requests', path: `${ROUTES.SP_MONITORING}/failed-requests`, icon: '⚠️' },
      { id: 'queue-jobs', label: 'Queue Jobs', path: `${ROUTES.SP_MONITORING}/queue-jobs`, icon: '🧵' },
    ],
  },
  {
    id: 'chat',
    label: 'Chat',
    path: ROUTES.SP_CHAT,
    icon: '💬',
    badge: '6',
  },
  {
    id: 'activities',
    label: 'Global Activities',
    path: ROUTES.SP_ACTIVITIES,
    icon: '🧾',
  },
  {
    id: 'announcements',
    label: 'Announcements',
    path: ROUTES.SP_ANNOUNCEMENTS,
    icon: '📢',
  },
  {
    id: 'settings',
    label: 'Settings',
    path: ROUTES.SP_SETTINGS,
    icon: '⚙️',
    children: [
      { id: 'general', label: 'General', path: `${ROUTES.SP_SETTINGS}/general`, icon: '📋' },
      { id: 'integration', label: 'Integrations', path: `${ROUTES.SP_SETTINGS}/integrations`, icon: '🔗' },
      { id: 'security', label: 'Security', path: `${ROUTES.SP_SETTINGS}/security`, icon: '🔐' },
    ],
  },
]
